#ifndef _KP_LSMDEF_H_
#define _KP_LSMDEF_H_

// /include/linux/lsm_hooks.h

typedef unsigned char LSM_VAL;

#define LSM_VAL_IGNORE 0
#define LSM_VAL_ALL 0xff

typedef enum LSM_TYPE
{
    LSM_TYPE_MIN = 0,
    LSM_TYPE_security_binder_set_context_mgr,
    LSM_TYPE_security_binder_transaction,
    LSM_TYPE_security_binder_transfer_binder,
    LSM_TYPE_security_binder_transfer_file,
    LSM_TYPE_security_ptrace_access_check,
    LSM_TYPE_security_ptrace_traceme,
    LSM_TYPE_security_capget,
    LSM_TYPE_security_capset,
    LSM_TYPE_security_capable,
    LSM_TYPE_security_quotactl,
    LSM_TYPE_security_quota_on,
    LSM_TYPE_security_syslog,
    LSM_TYPE_security_settime64,
    LSM_TYPE_security_vm_enough_memory_mm,
    LSM_TYPE_security_bprm_creds_for_exec,
    LSM_TYPE_security_bprm_creds_from_file,
    LSM_TYPE_security_bprm_check,
    LSM_TYPE_security_bprm_committing_creds,
    LSM_TYPE_security_bprm_committed_creds,
    LSM_TYPE_security_fs_context_dup,
    LSM_TYPE_security_fs_context_parse_param,
    LSM_TYPE_security_sb_alloc,
    LSM_TYPE_security_sb_delete,
    LSM_TYPE_security_sb_free,
    LSM_TYPE_security_free_mnt_opts,
    LSM_TYPE_security_sb_eat_lsm_opts,
    LSM_TYPE_security_sb_remount,
    LSM_TYPE_security_sb_kern_mount,
    LSM_TYPE_security_sb_show_options,
    LSM_TYPE_security_sb_statfs,
    LSM_TYPE_security_sb_mount,
    LSM_TYPE_security_sb_umount,
    LSM_TYPE_security_sb_pivotroot,
    LSM_TYPE_security_sb_set_mnt_opts,
    LSM_TYPE_security_sb_clone_mnt_opts,
    LSM_TYPE_security_add_mnt_opt,
    LSM_TYPE_security_move_mount,
    LSM_TYPE_security_dentry_init_security,
    LSM_TYPE_security_dentry_create_files_as,

    //config_security_path
    LSM_TYPE_security_path_unlink,
    LSM_TYPE_security_path_mkdir,
    LSM_TYPE_security_path_rmdir,
    LSM_TYPE_security_path_mknod,
    LSM_TYPE_security_path_truncate,
    LSM_TYPE_security_path_symlink,
    LSM_TYPE_security_path_link,
    LSM_TYPE_security_path_rename,
    LSM_TYPE_security_path_chmod,
    LSM_TYPE_security_path_chown,
    LSM_TYPE_security_path_chroot,
    /* config_security_path */

    /* needed for inode based security check */
    LSM_TYPE_security_path_notify,
    LSM_TYPE_security_inode_alloc,
    LSM_TYPE_security_inode_free,
    LSM_TYPE_security_inode_init_security,
    LSM_TYPE_security_old_inode_init_security,
    LSM_TYPE_security_inode_create,
    LSM_TYPE_security_inode_link,
    LSM_TYPE_security_inode_unlink,
    LSM_TYPE_security_inode_symlink,
    LSM_TYPE_security_inode_mkdir,
    LSM_TYPE_security_inode_rmdir,
    LSM_TYPE_security_inode_mknod,
    LSM_TYPE_security_inode_rename,
    LSM_TYPE_security_inode_readlink,
    LSM_TYPE_security_inode_follow_link,
    LSM_TYPE_security_inode_permission,
    LSM_TYPE_security_inode_setattr,
    LSM_TYPE_security_inode_getattr,
    LSM_TYPE_security_inode_setxattr,
    LSM_TYPE_security_inode_post_setxattr,
    LSM_TYPE_security_inode_getxattr,
    LSM_TYPE_security_inode_listxattr,
    LSM_TYPE_security_inode_removexattr,
    LSM_TYPE_security_inode_set_acl,
    LSM_TYPE_security_inode_get_acl,
    LSM_TYPE_security_inode_remove_acl,
    LSM_TYPE_security_inode_need_killpriv,
    LSM_TYPE_security_inode_killpriv,
    LSM_TYPE_security_inode_getsecurity,
    LSM_TYPE_security_inode_setsecurity,
    LSM_TYPE_security_inode_listsecurity,
    LSM_TYPE_security_inode_getsecid,
    LSM_TYPE_security_inode_copy_up,
    LSM_TYPE_security_inode_copy_up_xattr,
    LSM_TYPE_security_kernfs_init_security,
    LSM_TYPE_security_file_permission,
    LSM_TYPE_security_file_alloc,
    LSM_TYPE_security_file_free,
    LSM_TYPE_security_file_ioctl,
    LSM_TYPE_security_mmap_addr,
    LSM_TYPE_security_mmap_file,
    LSM_TYPE_security_file_mprotect,
    LSM_TYPE_security_file_lock,
    LSM_TYPE_security_file_fcntl,
    LSM_TYPE_security_file_set_fowner,
    LSM_TYPE_security_file_send_sigiotask,
    LSM_TYPE_security_file_receive,
    LSM_TYPE_security_file_open,
    LSM_TYPE_security_file_truncate,
    LSM_TYPE_security_task_alloc,
    LSM_TYPE_security_task_free,
    LSM_TYPE_security_cred_alloc_blank,
    LSM_TYPE_security_cred_free,
    LSM_TYPE_security_prepare_creds,
    LSM_TYPE_security_transfer_creds,
    LSM_TYPE_security_cred_getsecid,
    LSM_TYPE_security_kernel_act_as,
    LSM_TYPE_security_kernel_create_files_as,
    LSM_TYPE_security_kernel_module_request,
    LSM_TYPE_security_kernel_load_data,
    LSM_TYPE_security_kernel_post_load_data,
    LSM_TYPE_security_kernel_read_file,
    LSM_TYPE_security_kernel_post_read_file,
    LSM_TYPE_security_task_fix_setuid,
    LSM_TYPE_security_task_fix_setgid,
    LSM_TYPE_security_task_fix_setgroups,
    LSM_TYPE_security_task_setpgid,
    LSM_TYPE_security_task_getpgid,
    LSM_TYPE_security_task_getsid,
    LSM_TYPE_security_current_getsecid_subj,
    LSM_TYPE_security_task_getsecid_obj,
    LSM_TYPE_security_task_getsecid,
    LSM_TYPE_security_task_setnice,
    LSM_TYPE_security_task_setioprio,
    LSM_TYPE_security_task_getioprio,
    LSM_TYPE_security_task_prlimit,
    LSM_TYPE_security_task_setrlimit,
    LSM_TYPE_security_task_setscheduler,
    LSM_TYPE_security_task_getscheduler,
    LSM_TYPE_security_task_movememory,
    LSM_TYPE_security_task_kill,
    LSM_TYPE_security_task_prctl,
    LSM_TYPE_security_task_to_inode,
    LSM_TYPE_security_create_user_ns,
    LSM_TYPE_security_ipc_permission,
    LSM_TYPE_security_ipc_getsecid,
    LSM_TYPE_security_msg_msg_alloc,
    LSM_TYPE_security_msg_msg_free,
    LSM_TYPE_security_msg_queue_alloc,
    LSM_TYPE_security_msg_queue_free,
    LSM_TYPE_security_msg_queue_associate,
    LSM_TYPE_security_msg_queue_msgctl,
    LSM_TYPE_security_msg_queue_msgsnd,
    LSM_TYPE_security_msg_queue_msgrcv,
    LSM_TYPE_security_shm_alloc,
    LSM_TYPE_security_shm_free,
    LSM_TYPE_security_shm_associate,
    LSM_TYPE_security_shm_shmctl,
    LSM_TYPE_security_shm_shmat,
    LSM_TYPE_security_sem_alloc,
    LSM_TYPE_security_sem_free,
    LSM_TYPE_security_sem_associate,
    LSM_TYPE_security_sem_semctl,
    LSM_TYPE_security_sem_semop,
    LSM_TYPE_security_d_instantiate,
    LSM_TYPE_security_getprocattr,
    LSM_TYPE_security_setprocattr,
    LSM_TYPE_security_netlink_send,
    LSM_TYPE_security_ismaclabel,
    LSM_TYPE_security_secid_to_secctx,
    LSM_TYPE_security_secctx_to_secid,
    LSM_TYPE_security_release_secctx,
    LSM_TYPE_security_inode_invalidate_secctx,
    LSM_TYPE_security_inode_notifysecctx,
    LSM_TYPE_security_inode_setsecctx,
    LSM_TYPE_security_inode_getsecctx,

    // config_watch_queue
    LSM_TYPE_security_post_notification,

    // config_key_notifications
    LSM_TYPE_security_watch_key,

    // config_security_network
    LSM_TYPE_security_unix_stream_connect,
    LSM_TYPE_security_unix_may_send,
    LSM_TYPE_security_socket_create,
    LSM_TYPE_security_socket_post_create,
    LSM_TYPE_security_socket_socketpair,
    LSM_TYPE_security_socket_bind,
    LSM_TYPE_security_socket_connect,
    LSM_TYPE_security_socket_listen,
    LSM_TYPE_security_socket_accept,
    LSM_TYPE_security_socket_sendmsg,
    LSM_TYPE_security_socket_recvmsg,
    LSM_TYPE_security_socket_getsockname,
    LSM_TYPE_security_socket_getpeername,
    LSM_TYPE_security_socket_getsockopt,
    LSM_TYPE_security_socket_setsockopt,
    LSM_TYPE_security_socket_shutdown,
    LSM_TYPE_security_sock_rcv_skb,
    LSM_TYPE_security_socket_getpeersec_stream,
    LSM_TYPE_security_socket_getpeersec_dgram,
    LSM_TYPE_security_sk_alloc,
    LSM_TYPE_security_sk_free,
    LSM_TYPE_security_sk_clone,
    LSM_TYPE_security_sk_classify_flow,
    LSM_TYPE_security_req_classify_flow,
    LSM_TYPE_security_sock_graft,
    LSM_TYPE_security_inet_conn_request,
    LSM_TYPE_security_inet_csk_clone,
    LSM_TYPE_security_inet_conn_established,
    LSM_TYPE_security_secmark_relabel_packet,
    LSM_TYPE_security_secmark_refcount_inc,
    LSM_TYPE_security_secmark_refcount_dec,
    LSM_TYPE_security_tun_dev_alloc_security,
    LSM_TYPE_security_tun_dev_free_security,
    LSM_TYPE_security_tun_dev_create,
    LSM_TYPE_security_tun_dev_attach_queue,
    LSM_TYPE_security_tun_dev_attach,
    LSM_TYPE_security_tun_dev_open,
    LSM_TYPE_security_sctp_assoc_request,
    LSM_TYPE_security_sctp_bind_connect,
    LSM_TYPE_security_sctp_sk_clone,
    LSM_TYPE_security_sctp_assoc_established,

    // config_security_infiniband
    LSM_TYPE_security_ib_pkey_access,
    LSM_TYPE_security_ib_endport_manage_subnet,
    LSM_TYPE_security_ib_alloc_security,
    LSM_TYPE_security_ib_free_security,

    // config_security_network_xfrm
    LSM_TYPE_security_xfrm_policy_alloc,
    LSM_TYPE_security_xfrm_policy_clone,
    LSM_TYPE_security_xfrm_policy_free,
    LSM_TYPE_security_xfrm_policy_delete,
    LSM_TYPE_security_xfrm_state_alloc,
    LSM_TYPE_security_xfrm_state_alloc_acquire,
    LSM_TYPE_security_xfrm_state_delete,
    LSM_TYPE_security_xfrm_state_free,
    LSM_TYPE_security_xfrm_policy_lookup,
    LSM_TYPE_security_xfrm_state_pol_flow_match,
    LSM_TYPE_security_xfrm_decode_session,
    LSM_TYPE_security_skb_classify_flow,

    /* key management security hooks */
    // config_keys
    LSM_TYPE_security_key_alloc,
    LSM_TYPE_security_key_free,
    LSM_TYPE_security_key_permission,
    LSM_TYPE_security_key_getsecurity,

    // config_audit
    LSM_TYPE_security_audit_rule_init,
    LSM_TYPE_security_audit_rule_known,
    LSM_TYPE_security_audit_rule_free,
    LSM_TYPE_security_audit_rule_match,

    // config_bpf_syscall
    LSM_TYPE_security_bpf,
    LSM_TYPE_security_bpf_map,
    LSM_TYPE_security_bpf_prog,
    LSM_TYPE_security_bpf_map_alloc,
    LSM_TYPE_security_bpf_prog_alloc,
    LSM_TYPE_security_bpf_map_free,
    LSM_TYPE_security_bpf_prog_free,
    // config_bpf_syscall

    LSM_TYPE_security_locked_down,

    // config_perf_events
    LSM_TYPE_security_perf_event_open,
    LSM_TYPE_security_perf_event_alloc,
    LSM_TYPE_security_perf_event_free,
    LSM_TYPE_security_perf_event_read,
    LSM_TYPE_security_perf_event_write,

    // config_io_uring
    LSM_TYPE_security_uring_override_creds,
    LSM_TYPE_security_uring_sqpoll,
    LSM_TYPE_security_uring_cmd,

    //
    LSM_TYPE_MAX,
} LSM_TYPE;

#define LSM_TYPE_INVALID LSM_TYPE_MAX

static inline int lsm_type_valid(LSM_TYPE type)
{
    return type > LSM_TYPE_MIN && type < LSM_TYPE_MAX;
}

#endif
